### ISSUE TITLE
The export option doesn't seem to run in windows powershell

### ISSUE THREAD

**Issue by a6k7rii** [SUSE-Rancher-Community/rancher-desktop-example#1]
I was going through launching the demo wordpress app as per the Readme and faced the below issues. Help me get over this.
![Screenshot 2022-02-03 101446](https://user-images.githubusercontent.com/67803315/152371071-db9eb2c5-e1e6-4628-9c59-237a5b5a49c9.jpg)

**Comment by zoopster** [comment]
Try just using `kubectl get svc --namespace default demowp-wordpress` which will give you a lot of data, but you will find the URL  you need in that dump.

**Comment by a6k7rii** [comment]
Will do it.. and update the results..
